"""initial tables
Revision ID: 984b57f9d331                                                                                                                                                                                                                                                                                       
Revises: 
Create Date: 2026-04-10 19:05:10.101734                                                                                                                                                                                                                                                                                       
                
"""
from alembic import op
import sqlalchemy as sa

revision = '984b57f9d331'                                                                                                                                                                                                                                                                                   
down_revision = None
branch_labels = None                                                                                                                                                                                                                                                                            
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
def downgrade():                                                                                                                                                                                                                                                                                                  
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
