"""fix status column length
Revision ID: 9998e43c816d                                                                                                                                                                                                                                                                                       
Revises: 984b57f9d331
Create Date: 2026-04-11 08:38:00.667760                                                                                                                                                                                                                                                                                       
                
"""
from alembic import op
import sqlalchemy as sa

revision = '9998e43c816d'                                                                                                                                                                                                                                                                                   
down_revision = '984b57f9d331'
branch_labels = None                                                                                                                                                                                                                                                                            
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hasil_topsis', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
def downgrade():                                                                                                                                                                                                                                                                                                  
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hasil_topsis', 'status',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
